export const Config = {
  GOOGLE_CLOUD_IOS_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_CLOUD_IOS_API_KEY,
  GOOGLE_CLOUD_ANDROID_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_CLOUD_ANDROID_API_KEY,
  STRIPE_PUBLISHABLE_API_KEY: process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_API_KEY,
}
